name: Changed file in an array

on:
  workflow_dispatch:


jobs:
  check-changed:
    runs-on: ubuntu-20.04
    steps:
      - id: check-dependabot
        run: |
          is_dependabot=0
          if [ ${{ github.actor == 'deepankarm' }} ] || [ ${{ github.actor == 'deepankard' }} ]; then
            is_dependabot=1
          fi
          echo "::set-output name=is_dependabot::${is_dependabot}"
      - run: |
          echo "${{ steps.check-dependabot.outputs.is_dependabot }} is "
      - id: changed-files
        uses: jitterbit/get-changed-files@v1
      - run: |
          echo ${{ steps.file_changes.outputs.all }}
          echo ${{ steps.file_changes.outputs.removed }}
        env:
          CHANGED_FILES: ${{ steps.file_changes.outputs.all }}
          REMOVED_FILES: ${{ steps.file_changes.outputs.removed }}

