name: 'Test job'

on: 
  workflow_dispatch:
    inputs:
      TFID:
        description: 'Pass the TFID for the deployment data to be fetched'
        required: true

jobs:
  new-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - uses: hashicorp/setup-terraform@v1

      - run: >
          terraform init -force-copy
          -backend-config="bucket=jina-tf-states"
          -backend-config="region=us-east-1"
          -backend-config="key=${{ github.event.inputs.TFID }}"
          working-directory: ./daemon-deployment

      - run: terraform output
        working-directory: ./daemon-deployment
