name: Generate

on:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.2.0
        with:
          fetch-depth: 0
      - name: Get Previous tag
        id: previoustag
        uses: WyriHaximus/github-action-get-previous-tag@v1
        with:
          fallback: 0.0.0
      - name: Get next minor version
        id: semvers
        uses: WyriHaximus/github-action-next-semvers@v1
        with:
          version: ${{ steps.previoustag.outputs.tag }}
          
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.semvers.outputs.patch }}
          release_name: Release ${{ steps.semvers.outputs.patch }}
          body: Release ${{ steps.semvers.outputs.patch }}
          draft: false
          prerelease: false
          
#       - name: Create new milestone
#         id: createmilestone
#         uses: WyriHaximus/github-action-create-milestone@v1
#         with:
#           title: ${{ steps.semvers.outputs.patch }}
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
