name: Manual Release

on:
  workflow_dispatch:
    inputs:
      release_token:
        description: Your release token
        required: true
      release_reason:
        description: Short reason for this manual release
        required: true

jobs:
  token-check:
    runs-on: ubuntu-latest
    steps:
      - run: echo "success!"
        if: "${{ github.event.inputs.release_token }} == ${{ env.release_token }}"
        env:
          release_token: ${{ secrets.DOCSBOT_RELEASE_TOKEN }}
  
  regular-release:
    needs: token-check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.2.0
        with:
          fetch-depth: 0
      - name: Get Previous tag
        id: previoustag
        uses: WyriHaximus/github-action-get-previous-tag@v1
        with:
          fallback: 0.0.0
      - name: Get next minor version
        id: semvers
        uses: WyriHaximus/github-action-next-semvers@v1
        with:
          version: ${{ steps.previoustag.outputs.tag }}
          
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.semvers.outputs.patch }}
          release_name: Release ${{ steps.semvers.outputs.patch }}
          body: ${{ github.event.inputs.release_reason }}
          draft: false
          prerelease: false
