name: pull_request

on:
  pull_request:
  workflow_dispatch:


jobs:
  pull_request_check:
    runs-on: ubuntu-20.04
    steps:
      - run: |
          curl --location --request GET 'https://api.github.com/user' --header 'Authorization: token ${{ secrets.MY_JINAHUB_TOKEN}}'
          curl --location --request GET 'https://api.github.com/user' --header 'Authorization: token ${{ github.token }}'
          
