name: Redoc tests

on:
  workflow_dispatch:


jobs:
  update-docs:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          repository: jina-ai/jina
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: |
          pip install .[daemon] --no-cache-dir
          python scripts/get-gateway-openapi.py
          npm install --prefix ~ snippet-enricher-cli
          ~/node_modules/.bin/snippet-enricher-cli --input=gateway.json --targets=shell_curl > openapi-with-examples.json
          cat openapi-with-examples.json
      - name: redoc-cli-gateway
        uses: seeebiii/redoc-cli-github-action@v10
        with:
          args: 'bundle openapi-with-examples.json -o rest.html'
