name: Deploy stuff

on:
  workflow_dispatch:
    inputs:
      branch:
        description: Pass the jina-operator branch
        required: false
        default: main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      
      - name: Slack Notification
        uses: 8398a7/action-slack@v3
        with:
          status: custom
          fields: workflow,job,commit,repo,ref,author,took
          custom_payload: |
            {
              attachments: [{
                text: `Who took over the CI? :point_right: ${process.env.AS_AUTHOR} Branch: ${{ github.event.inputs.branch }}`,
              }]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
